export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_BY_AMOUNT = "INCREMENT_BY_AMOUNT";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";
export const RESET_COUNTER = "RESET_COUNTER";

export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_FULFILLED = "FETCH_TODOS_FULFILLED";
export const RESET_TODOS = "RESET_TODOS";
